### ISSUE TITLE
L3AF page should use eBPF program not kernel function

### ISSUE THREAD

**Issue by dthaler** [NgKore47/docs#6]
The L3AF project now uses "eBPF program" not "kernel function".
[l3af.rst](https://github.com/NgKore47/docs/blob/main/docs/l3af/l3af.rst) should be updated to be consistent with the L3AF project.

**Comment by evershalik** [comment]
Thanks for the update @dthaler. We will update this soon.

**Comment by AdityaKoranga** [comment]
This issue is resolved according to the PR #7.
